### ISSUE TITLE
Application Crash While Trying To Login

### ISSUE THREAD

**Issue by wax911** [AniTrend/anitrend-app#84]
# AniTrend Issue

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/AniTrend/anitrend-app/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/AniTrend/anitrend-app/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

- [x] Bug
- [ ] Feature

# Current Behaviour

Application crashes immediately after tapping on the login entry in the navigation drawer

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

1. Open navigation drawer
2. Tap on `Sign In`
3. Application will hang for a second then crash

## Context

* OS Version: 4.2.X
* Phone Model: Duos 2
* Phone Brand: Samsung

## Failure Logs

```log
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mxt.anitrend/com.mxt.anitrend.view.activity.index.LoginActivity}: android.view.InflateException: Binary XML file line #18: Error inflating class <unknown>
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2372)
Caused by android.content.res.Resources$NotFoundException: File res/drawable/material_curve.xml from drawable resource ID #0x7f080151
       at android.content.res.Resources.loadDrawable(Resources.java:1993)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
Caused by java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
       at android.content.res.TypedArray.getColor(TypedArray.java:326)
       at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:967)
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:885)
       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
```

**Comment by wax911** [comment]
Issue has been fixed on commit [57162ddfed9133ce06b07398cff50f2515a18162](https://github.com/AniTrend/anitrend-app/commit/57162ddfed9133ce06b07398cff50f2515a18162)
